---
title: "Follow-up of the Covid-19 breakdown"
author: "Mouhamdou M. Sy"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
library(DT)
library(dygraphs)
library(dplyr)
library(ggplot2)
library(htmlwidgets)
library(htmltools)
library(RColorBrewer)
library(sp)

source("C:/Users/mouha/OneDrive/Documents/Data_Science_Projects/Project_1_DataViz/covid19_dashboard/data_preprocessing.R")
```

Global Situation
=======================================================================

Row {data-height = 100}
-----------------------------------------------------------------------

### Confirmed Cases
```{r}
load("Confirmed_ldav.rdata")
valueBox(Confirmed_ldav, color = "grey", icon ="fa-clinic-medical")
```

### Recovored Cases
```{r}
load("Recovered_ldav.rdata")
valueBox(Recovered_ldav, color = "green", icon ="fa-heart")
```

### Death Cases
```{r}
load("Confirmed_ldav.rdata")
load("Deaths_ldav.rdata")
value = round(Deaths_ldav/Confirmed_ldav*100, 2)
gauge(value, min = 0, max = 100, symbol = '%')
```

### Total number of cases at the last date available

```{r}
load("cntries_agg_lastdateav.rdata")
load("last_date_available.rdata")

data <- cntries_agg_lastdateav %>%
  arrange(Cont_Reg) %>%
  group_by(Cont_Reg) %>%
  rename(Continent_Region = Cont_Reg) %>%
  summarise(Confirmed = sum(Confirmed), Recovered = sum(Recovered), Deaths = sum(Deaths))

DT::datatable(data, options = list(bPaginate = FALSE, autoWidth = TRUE), 
    caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',                                'Table 1: ',htmltools::em(paste("Number of total cases per continent on ",last_date_available, sep =""))),
    filter = "none",
    colnames = c("Continent/Region" = "Continent_Region"),
    rownames = FALSE)
```


Row {data-heigh = 900}
-----------------------------------------------------------------------

### Map of the number of confirmed cases worldwide

```{r}
load("cntries_agg.rdata")
load("last_date_available.rdata")

# Example of map illustration with the data
data_map_ldav = cntries_agg %>%
                  arrange(Date) %>%
                  filter(Date == last_date_available)

# Create a palette that maps factor levels to colors
col_pal  = c(brewer.pal(n = 3, name = "Paired")[1],
             brewer.pal(n = 3, name = "Paired")[2],
             brewer.pal(n = 3, name = "Dark2")[1],
             brewer.pal(n = 7, name = "Reds")[5],
             brewer.pal(n = 7, name = "Reds")[6],
             brewer.pal(n = 7, name = "Reds")[7])
pal      = colorFactor(col_pal, domain = paste("c",1:6,sep=""))

map_ldav = leaflet(data = data_map_ldav) %>% 
  addTiles() %>%
  addCircleMarkers(lat = ~ lat_,
                   lng = ~ long_,
                   radius = ~ Rad,
                   color  = ~ pal(Bin),
                   stroke = FALSE,
                   fillOpacity = 0.5) %>%
  addLabelOnlyMarkers(label=~htmlEscape(paste("Confirmed Cases = ",Confirmed,sep="")),lat=~lat_,lng=~long_)
map_ldav
```

### Daily evolution of the situation

```{r}
load("ww_agg_xts.Rdata")
dygraphs::dygraph(data = ww_agg_xts, xlab = "Date", ylab = "Number of Cases") %>%
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 20)
```

Country-specific Situation
======================================================================

Column {data-width = 300}
----------------------------------------------------------------------

### Number of cases per region

```{r}
load("dat.tab.3.cntries.rdata")
load("last_date_available.rdata")

dat = dat.tab %>%
  filter(Country == "Germany") %>%
  dplyr::select(Province_Region, Cases)
  
DT::datatable(dat, 
              options = list(bPaginate = TRUE, autoWidth = TRUE),
              caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',                                'Table 2: ',htmltools::em(paste("Number of total cases in Germany on ",last_date_available, sep =""))),
              filter = "none",
              rownames = FALSE)

```

Column {data-width=700}
----------------------------------------------------------------------

### Screenshot of the spatial distribution 

```{r}
# Loading the required data
load("last_date_available.rdata")
load("de_faellen.rdata")

# Create the palette of colors
Bins_cases = c(0, 10^(1:7))
Pal_world  = colorBin(palette = "YlOrRd", domain = de_faellen$Fallzahl, bins = Bins_cases)
#c(0,10^7)

## Labels
de_faellen$labels = paste0("<strong> Region: </strong> ", de_faellen$LAN_ew_GEN, "<br/> ",
                           "<strong> Cases: </strong> ", de_faellen$Fallzahl, "<br/") %>%
  lapply(htmltools::HTML)
  
## Plot the map
renderLeaflet({
m = leaflet(data = de_faellen) %>%
    addTiles() %>%
    setView(lng = 9.5, lat = 52., zoom = 6.2) %>%
    addPolygons(
                fillColor   = ~ Pal_world(Fallzahl),
                color       = "white",
                fillOpacity = 0.7,
                label       = ~ labels,
                highlight   = highlightOptions(color = "black", bringToFront = TRUE)) %>%
    leaflet::addLegend(pal = Pal_world,
                       values = ~Fallzahl,
                       opacity = 0.7,
                       title = "Number of cases")
m
})
```


Dynamic Evolution Worlwide
======================================================================

Column {.sidebar data-width=200}
----------------------------------------------------------------------

```{r}
## Loading the required information
load("last_date_available.rdata") # Loading the value of the last date available
load("covid19_world_data.rdata")  # Loading the Covid19 time series data 

brk.down_dates = unique(as.Date(covid_dat$Date))
L = length(brk.down_dates)

shiny::sliderInput("dates",
            label   = "Select a date for the map",
            min     = brk.down_dates[1],
            max     = brk.down_dates[L],
            value   = brk.down_dates[1],
            timeFormat = "%F")
            #choices = unique(as.character(covid_dat$Date)))

### Add here a selectInput Space for the selection of the countries to show

shiny::selectInput(inputId = "cntry",
                   label = "Select a country",
                   choices = unique(as.character(covid_dat$Country)))
```

Column {data-width=500}
----------------------------------------------------------------------

### Dynamic evolution of the breakdown over the World

```{r}
## Loading the required data and map
load("covid19_world_map.rdata")   # Loading the map file
load("covid19_world_data.rdata")  # Loading the Covid19 time series data 

## Create the color Palette and the bins of case values
Bins_world = c(0, 10^(1:7))
Pal_world  = colorBin(palette = "YlOrRd", domain = c(0, 10^7), bins = Bins_world)

## Extract the selected data using the reactive function
mapFiltered = reactive({
  
  map_data = covid_dat %>%
    filter(Date == as.character(input$dates))
  map_data = map_data[order(match(map_data$Country,covid_map$Country)),]
  
})

labelsFiltered = reactive({
  paste0("<strong> Country: </strong> ", mapFiltered()$Country, "<br/> ",
         "<strong> Cases: </strong> "  , mapFiltered()$Confirmed, "<br/> ",
         "<strong> (Deaths: </strong> ", mapFiltered()$Deaths, ") <br/") %>%
    lapply(htmltools::HTML)
})

## Create the map
renderLeaflet({
  
  leaflet(covid_map) %>%
  addTiles() %>%
  setView(lng = 0, lat = 0, zoom = 2) %>%
  addPolygons(fillColor = Pal_world(mapFiltered()$Confirmed),
              color = "white",
              fillOpacity = 0.7,
              label = labelsFiltered(),
              highlight = highlightOptions(color = "black", bringToFront = TRUE)) %>%
  leaflet::addLegend(pal = Pal_world, values = mapFiltered()$Confirmed, opacity = 0.7, title = "Number of cases")
})
```

### Evolution of the breakdown for a selected country

```{r}
## Load the required information
load("last_date_available.rdata")
load("covid19_world_data.rdata")  # Loading the Covid19 time series data 

## Reactive function 
cntrySelected = reactive({
  data_cntry = covid_dat %>%
    filter(Country == input$cntry) %>%
    arrange(Date) %>%
    select(Country, Date, Confirmed, Recovered, Deaths) %>%
    mutate(Death.Rate = round(100*(Deaths/Confirmed), 2) ) %>%
    select(Country, Date, Confirmed, Recovered, Death.Rate)

})

## Create the table
renderDT({
  data_tab = cntrySelected()
  DT::datatable(data_tab, 
                class = 'cell-border stripe',
                options = list(bPaginate = TRUE, autoWidth = TRUE),
                caption = htmltools::tags$caption(style = 'caption-side: top; text-align: center;',                                'Table 3: ',htmltools::em(paste("Number of total cases per country on ",last_date_available, sep =""))),
                filter = "none",
                #colnames = c("Death.Rate" = "Death Rate (in %)"),
                rownames = FALSE)
  })
```

